### ISSUE TITLE
Ideias de Nome para o aplicativo

### ISSUE THREAD

**Issue by micaellagouveia** [fga-eps-mds/2021.1-Linguas-Indigenas-Docs#33]
### Descrição da *issue*
Listar ideias para o nome do aplicativo.

**Comment by micaellagouveia** [comment]
Ideia 1: Mapa Indígena
Ideia 2: IndigenousMap

**Comment by CarlosZoft** [comment]
Ideia 5: Relato Indígena
Ideia 6: Afluência Indígena
Ideia 7: Nativamente Indígena

**Comment by pedroeagle** [comment]
Ideia 8: Andira
Ideia 9: Mapeia

**Comment by hericklima22** [comment]
Ideia 10: Mapper
Ideia 11: IndyMap

**Comment by sofiapatrocinio** [comment]
Ideia 12: Língua Falada
Ideia 13: Brasil Multilíngue
Ideia 14: Identidade Indígena
Ideia 15: Retrato Indígena
Ideia 16: Além do Português
