### ISSUE TITLE
Protótipo de Baixa Fidelidade

### ISSUE THREAD

**Issue by micaellagouveia** [fga-eps-mds/2021.1-Linguas-Indigenas-Docs#43]
### Descrição da *issue*
Desenvolvimento de protótipos de baixa fidelidade.

### Tarefas
Herick e Helder

- [x] Usuário Admin: Cadastro admin, Controle de usuários
- [x] Mapeamento: Mapa com as línguas, Divisão por tronco linguístico (listagem)

Fael e Ingrid
- [x] Avaliação: Tela de publicação de novas informações, Tela de envio para os adms, Tela de Aprovação do conteúdo (Dados da pessoa que aprovou e enviou)
- [x] Língua específica: Dados da lingua, imagens, Povos que falam a língua

### Critérios de aceitação
- [x] Fotos documentadas na issue

**Comment by hericklima22** [comment]
Telas de controle de controle de usuários:

![printsolo](https://user-images.githubusercontent.com/48794282/130162569-9d392b1a-4df6-4b46-99dc-4fa64a2bedad.png)

**Comment by hericklima22** [comment]
Tela de criação de admin:

![Screenshot_2](https://user-images.githubusercontent.com/48794282/130163542-b19c9a65-fad7-4e33-9434-9f1392ecc263.png)

**Comment by F1reFinger** [comment]
![tela 1](https://user-images.githubusercontent.com/78388335/130163788-f3520889-57a1-4bec-9b41-34ddb84d38bc.png)

**Comment by F1reFinger** [comment]
![tela 2](https://user-images.githubusercontent.com/78388335/130163842-46bb9bd2-9cab-4a4c-9f6a-c5896d982ebd.png)

**Comment by F1reFinger** [comment]
![novo](https://user-images.githubusercontent.com/78388335/130239508-a5980463-adcb-4c33-be65-f8aa8493ba33.png)
![H_novo](https://user-images.githubusercontent.com/78388335/130239512-5c46768f-7a31-48e4-9c3c-a15d1b41c38c.png)
![criação_admin](https://user-images.githubusercontent.com/78388335/130239515-c28f7786-b3c0-4478-99a2-8cdbdf865589.png)

**Comment by micaellagouveia** [comment]
> Telas de controle de controle de usuários:
> 
> ![printsolo](https://user-images.githubusercontent.com/48794282/130162569-9d392b1a-4df6-4b46-99dc-4fa64a2bedad.png)

Aqui podemos mudar o nome tribo para povo :)

**Comment by CarlosZoft** [comment]
![image](https://user-images.githubusercontent.com/62192072/130244456-25d3c8e7-1b8e-4adc-be71-5c7007c12062.png)
![image](https://user-images.githubusercontent.com/62192072/130245066-198013ee-df31-443e-ad11-84e9f1302b76.png)
![image](https://user-images.githubusercontent.com/62192072/130244594-ad3be86d-35b8-4926-b347-f71b8c2330e3.png)

**Comment by ingridSCarvalho** [comment]
![Tela de lingua específica](https://user-images.githubusercontent.com/69825746/130253195-996fa98f-bf4e-4a65-94d1-fe79c8bba6c1.png)
![Tela de publicação](https://user-images.githubusercontent.com/69825746/130253213-6f6e6a64-2b53-40b4-a1ab-abfc5cdf7740.png)
