### ISSUE TITLE
Representação Arquitetural

### ISSUE THREAD

**Issue by micaellagouveia** [fga-eps-mds/2021.1-Linguas-Indigenas-Docs#48]
### Descrição da *issue*
Desenvolver a Representação Arquitetural do Documento de Arquitetura

### Tarefas
- [x] NodeJS
- [ ] React Native
- [x] Firebase
- [ ] Docker
- [ ] MongoDB

### Critérios de aceitação
- [ ] Estar documentado na Wiki

**Comment by isadoragalvaoss** [comment]
## Contexto

O Línguas Indígenas Brasileiras é um aplicativo que visa ajudar a unir a comunidade falante de línguas bem como ajudar na tradução de palavras e na união entre os falantes nativos e os não-falantes.
Desenvolvida por nove graduandos do curso de Engenharia de Software, pelas disciplinas de Métodos de Desenvolvimento de  Software e Engenharia de Produto de Software com tempo estimado de cinco meses de desenvolvimento, tempo de duração da matéria.



## Tecnologias

### NodeJS
É um Ambiente de execução JavaScript fora do browser. Com flexibilidade, escala e fácil transferência de dados, que faz destacar principalmente a arquitetura de microsserviços, diminuindo custos e perdas causados por alto acoplamento.


### React Native
É um framework baseado no React, que possibilita o desenvolvimento de aplicações mobile (tanto para Android, quanto para iOS) utilizando a linguagem Javascript. O que diferencia o React Native dos outros frameworks, é que todo o código desenvolvido é convertido para linguagem nativa do sistema operacional, o que acaba tornando o aplicativo muito mais fluido. 


### FireBase
Plataforma de gerenciamento de banco de dados, onde é possível armazenar arquivos como vídeos, imagens, áudios etc. Também é possível gerenciar toda a área de login e cadastro de usuários. Acelera o desenvolvimento do App pois ele exclui quase que totalmente a parte de criação e gerenciamento de banco de dados, tornando mais fácil e prático de se desenvolver.


### PostgreSQL
Ferramenta utilizada como sistema gerenciador de banco de dados que permite produção de trabalhos padronizados da linguagem SQL em estruturas, garantindo a execução de consultas, facilidade de acesso e indexação por texto durante o armazenamento de dados


# Referências

* React Native: https://www.organicadigital.com/blog/o-que-e-react-native
* NodeJs:         https://www.opus-software.com.br/node-js/
* PostgreSQL:  https://rockcontent.com/br/blog/postgresql/
* Firebase: 	  https://firebase.google.com/?hl=pt
